on: [push]
jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Send Mail"
          body: |
            testing push 2
            ${{github.event.pusher.name}} repost
            ${{github.repository}} sõnumiga
            ${{github.event.head_commit.message}}
          to: jyri.vaitmaa@tthk.ee
          from: "GitHub Actions"
        